return {
    ThemeName = "Dark",

    BackgroundColor = Color3.fromRGB(26, 26, 26),
    DarkBackgroundColor = Color3.fromRGB(12, 12, 12),
    LightBackgroundColor = Color3.fromRGB(36, 36, 36),
    StrokeColor = Color3.fromRGB(48, 48, 48),
    ScrollbarColor = Color3.fromRGB(255, 255, 255),
    TextColor = Color3.fromRGB(255, 255, 255),
    PlaceholderTextColor = Color3.fromRGB(223, 223, 223),
    ButtonToggledColor = Color3.fromRGB(0, 0, 0),
    SliderFillColor = Color3.fromRGB(48, 48, 48),
    Font = Enum.Font.Arimo,
    ScrollBarThickness = 4,
    StrokeThickness = 1, 
    WindowBorderVisble = true
}