return {
    ThemeName = "Default",

    MenuEnabledBackgroundColor = Color3.fromRGB(85, 0, 127),
    MenuEnabledTransparency = 0.8,
    
    TabBackgroundColor = Color3.fromRGB(38, 38, 38),
    TextColor = Color3.fromRGB(170, 85, 255),
    
    ScrollBarThickness = 4,
    ScrollBarColor = Color3.fromRGB(170, 85, 255),

    ButtonBackgroundColor = Color3.fromRGB(38, 38, 38),
    ButtonToggledColor = Color3.fromRGB(170, 85, 255),
    ButtonHoverColor = Color3.fromRGB(170, 85, 255),
    ButtonToggledTextColor = Color3.fromRGB(0,0,0),
    ButtonBackgroundTransparency = 1,
}