return {
    BackgroundColor = Color3.fromRGB(26, 23, 29),
    DarkBackgroundColor = Color3.fromRGB(22, 18, 24),
    LightBackgroundColor = Color3.fromRGB(38, 32, 42),
    StrokeColor = Color3.fromRGB(228, 196, 255),
    ScrollbarColor = Color3.fromRGB(228, 196, 255),
    TextColor = Color3.fromRGB(240, 222, 255),
    ScrollBarThickness = 4,
    StrokeThickness = 1,
    WindowBorderVisble = true
}