return {
    ThemeName = "Light",

    BackgroundColor = Color3.fromRGB(223, 223, 223),
    DarkBackgroundColor = Color3.fromRGB(196, 196, 196),
    LightBackgroundColor = Color3.fromRGB(248, 248, 248),
    StrokeColor = Color3.fromRGB(255, 255, 255),
    ScrollbarColor = Color3.fromRGB(255, 255, 255),
    TextColor = Color3.fromRGB(211, 211, 211),
    PlaceholderTextColor = Color3.fromRGB(134, 134, 134),
    ButtonToggledColor = Color3.fromRGB(255, 255, 255),
    SliderFillColor = Color3.fromRGB(233, 233, 233),
    Font = Enum.Font.Arimo,
    ScrollBarThickness = 4,
    StrokeThickness = 1, 
    WindowBorderVisble = true
}